enyo.depends(
   "lib/AlarmController.js",
   "lib/DateUtils.js",
    "source/diliTimer.js",
    "source/Preferences.js",
    "source/About.js",
    "source/Help.js",
    "source/TimePickerGroup.js",
    "source/TimerController.js",
    "css/diliTimer.css"
)
